export * from "./SupplyByInternetSvg/SupplyByInternetSvg";
export * from "./SupplyByPhoneSvg/SupplyByPhoneSvg";
export * from "./SupplyInPersonSvg/SupplyInPersonSvg";
export * from "./TomanIconSvg/TomanIconSvg";
export * from "./CartSvg/CartSvg";
export * from "./CategoriesSvg/CategoriesSvg";
export * from "./HomeSvg/HomeSvg";
export * from "./MapSvg/MapSvg";
export * from "./UserSvg/UserSvg";
